package uk.gov.companieshouse.addresslookup.model;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

public record IslRoyalMailAddressDto(
        Integer udprn,
        LocalDate versionDate,
        LocalDateTime versionAvailableFromDate,
        LocalDateTime versionAvailableToDate,
        String changeType,
        String theme,
        String description,
        String organisationName,
        String departmentName,
        String subBuildingName,
        String buildingName,
        Integer buildingNumber,
        String dependentThoroughfare,
        String thoroughfare,
        String doubleDependentLocality,
        String dependentLocality,
        String postTown,
        String postcode,
        String postcodeType,
        String deliveryPointSuffix,
        String welshDependentThoroughfare,
        String welshThoroughfare,
        String welshDoubleDependentLocality,
        String welshDependentLocality,
        String welshPostTown,
        String poBoxNumber,
        LocalDate updateDate,
        LocalDate entryDate,
        BigDecimal easting,
        BigDecimal northing,
        BigDecimal latitude,
        BigDecimal longitude,
        String positionalAccuracy,
        String geometryAllocationMethod,
        String unmatchedReason,
        LocalDate unmatchedReasonDate,
        Long uprn,
        String matchedAddressFeatureType,
        String matchType,
        LocalDate matchDate,
        String matchMethod,
        String matchingOrganisation) {
}
