### Lookup addresses by postcode
GET http://localhost:8080/address-lookup-api/addresses?postcode=AB124NY

### Lookup multiple legacy addresses by postcode
GET http://localhost:8080/address-lookup-api/multiple-addresses?postcode=AB124NY

### Lookup multiple legacy addresses by postcode (ISL table)
GET http://localhost:8080/address-lookup-api/multiple-addresses?postcode=BT100EQ

### Lookup single legacy address by postcode
GET http://localhost:8080/address-lookup-api/postcode?postcode=WF27QD

### Lookup multiple addresses by postcode using Postcode API
GET https://postcode.cidev.aws.chdev.org/multiple-addresses/AB124NY
