spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/address_lookup}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.liquibase.change-log=classpath:db/changelog/db.changelog-local.yaml
spring.docker.compose.enabled=${DOCKER_COMPOSE_ENABLED:true}
